create table if not exists crm_order_product
(
    id integer generated by default as identity primary key,
    created_at timestamp(0) without time zone default NULL::timestamp without time zone,
    active boolean,
    sort int,
    price numeric(11, 2),
    code varchar(256),
    name varchar(256),
    description varchar(256),
    custom_fields jsonb
);

insert into crm_order_product (
  created_at, active, sort, price, code,
  name, description, custom_fields
)
select
  created_at,
  (random() > 0.5):: bool as active,
  sort,
  random_between(2000, 100000) as price,
  random_text(5, 5) AS code,
  random_text(10, 20) as name,
  random_text(50, 100) as description,
  jsonb_build_object(
    'error',
    (
      random() > 0.5
    ):: bool,
    'message',
    md5(
      random():: text
    )
  )
from
  generate_series(
    now() - interval '5 hour', now(), interval '1 minute'
  ) AS created_at,
  generate_series(1, 100, 1) AS sort;

CREATE EXTENSION pg_trgm;

CREATE EXTENSION btree_gist;
