version: '3.8'

volumes:
  postgres: ~

services:
  postgres:
    image: postgres:alpine
    container_name: ${APP_NAME}_postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PG_DB}", "-U", "${PG_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5