drop table if exists recipe;
drop table if exists medicine;
drop table if exists record_diagnosis;
drop table if exists diagnosis;
drop table if exists record;
drop table if exists doctor_position;
drop table if exists position;
drop table if exists doctor;
drop table if exists patient;